### ISSUE TITLE
Know issues / missing features

### ISSUE THREAD

**Issue by danielnordh** [bdgwallet/dailywallet#18]
- [ ] Restore existing wallet - not styled / won't work with lightning
- [ ] Create wallet advanced settings - not implemented
- [ ] Create wallet button - should have progress indicator or similar

**Comment by yashrajd** [comment]
- [x] Request – on-chain receive QR code & address reads as "no-address" for some time before showing the actual address

https://github.com/bdgwallet/dailywallet/assets/114083781/02843c7c-521c-435b-90b2-871805b82a2e

- [x] Request - Onchain/lightning toggle in the wrong location ([correct position](https://www.figma.com/file/lf2Xyw2I2OXPsHiFQVQdiG/Daily-spending-wallet-prototype?type=design&node-id=4152%3A308238&mode=design&t=6uKvzxrpRWv8LZFD-1))and (dark mode) Done button text colour hard to read

![IMG_6757](https://github.com/bdgwallet/dailywallet/assets/114083781/72635098-5460-4b35-849b-dff9370218b8)

**Comment by danielnordh** [comment]
Fixed in 0.3

**Comment by yashrajd** [comment]
I checked, and I'm still facing the 'no address' issue but I have new issue now, where the QR won't be displayed and I see a spinner instead.

![IMG_13BBD65870A9-1](https://github.com/user-attachments/assets/dc510ff3-c101-4dbb-8795-7392c2ae881b)

**Comment by danielnordh** [comment]
> I checked, and I'm still facing the 'no address' issue 

OK, I should disable the share and copy button until addresses are fetched (see JIT delay below)

> but I have new issue now, where the QR won't be displayed and I see a spinner instead.

This is expected while the app gets a JIT address.
It should resolve within a second or two.
Agree it would be better if this was not delayed, or handled better in the UI.
